/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbogui;

import java.sql.*;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author Asus
 */
public class pilihFilm extends javax.swing.JFrame {

    /**
     * Creates new form pilihFilm
     */
    public Connection kon;
    isi isi1 = new isi();
    DefaultComboBoxModel datafilm = new DefaultComboBoxModel();
    public pilihFilm() {
         initComponents();
         isikan();
        
    }
    private void isikan(){
        pilih.setModel(datafilm);
        
        isi1.isibox(datafilm);
    }
    
    public String baris, nomer;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilih = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cetakButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jamt = new javax.swing.JLabel();
        studio = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bangkuA1Button = new javax.swing.JButton();
        bangkuA2Button = new javax.swing.JButton();
        bangkuA3Button = new javax.swing.JButton();
        bangkuA4Button = new javax.swing.JButton();
        bangkuB1Button = new javax.swing.JButton();
        bangkuB2Button = new javax.swing.JButton();
        bangkuB3Button = new javax.swing.JButton();
        bangkuB4Button = new javax.swing.JButton();
        bangkuC1Button = new javax.swing.JButton();
        bangkuC2Button = new javax.swing.JButton();
        bangkuC3Button = new javax.swing.JButton();
        bangkuC4Button = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pilih Film        :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, -1));

        pilih.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        jPanel1.add(pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 19, 370, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Jam Tayang   :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Studio             :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Pilih Kursi      :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));

        cetakButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cetakButton.setText("Cetak Tiket");
        cetakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cetakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 134, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Harga             :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        jamt.setText("-");
        jPanel1.add(jamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 370, 20));

        studio.setText("-");
        jPanel1.add(studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 77, 390, 20));

        harga.setText("-");
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 390, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Layar");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bangkuA1Button.setText("A1");
        bangkuA1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA1ButtonActionPerformed(evt);
            }
        });

        bangkuA2Button.setText("A2");
        bangkuA2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA2ButtonActionPerformed(evt);
            }
        });

        bangkuA3Button.setText("A3");
        bangkuA3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA3ButtonActionPerformed(evt);
            }
        });

        bangkuA4Button.setText("A4");
        bangkuA4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuA4ButtonActionPerformed(evt);
            }
        });

        bangkuB1Button.setText("B1");
        bangkuB1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB1ButtonActionPerformed(evt);
            }
        });

        bangkuB2Button.setText("B2");
        bangkuB2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB2ButtonActionPerformed(evt);
            }
        });

        bangkuB3Button.setText("B3");
        bangkuB3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB3ButtonActionPerformed(evt);
            }
        });

        bangkuB4Button.setText("B4");
        bangkuB4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuB4ButtonActionPerformed(evt);
            }
        });

        bangkuC1Button.setText("C1");
        bangkuC1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC1ButtonActionPerformed(evt);
            }
        });

        bangkuC2Button.setText("C2");
        bangkuC2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC2ButtonActionPerformed(evt);
            }
        });

        bangkuC3Button.setText("C3");
        bangkuC3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC3ButtonActionPerformed(evt);
            }
        });

        bangkuC4Button.setText("C4");
        bangkuC4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangkuC4ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bangkuC1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuB1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuA1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bangkuA2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuC2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bangkuB2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bangkuC3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bangkuC4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bangkuA4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bangkuA3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bangkuB3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bangkuB4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bangkuA1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuA3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bangkuB1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuB2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuB3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuB4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bangkuC3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuC4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuC2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangkuC1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 420, 250));

        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        jPanel1.add(kembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 134, 40));

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 17, 82, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/3.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangkuC4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC4ButtonActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "4";
    }//GEN-LAST:event_bangkuC4ButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        new TampilanAwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void bangkuA1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA1ButtonActionPerformed
       // TODO add your handling code here:
       baris = "a";
       nomer = "1";
    }//GEN-LAST:event_bangkuA1ButtonActionPerformed

    private void bangkuA2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA2ButtonActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "2";
    }//GEN-LAST:event_bangkuA2ButtonActionPerformed

    private void bangkuA3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA3ButtonActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "3";
    }//GEN-LAST:event_bangkuA3ButtonActionPerformed

    private void bangkuA4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuA4ButtonActionPerformed
        // TODO add your handling code here:
        baris = "a";
        nomer = "4";
    }//GEN-LAST:event_bangkuA4ButtonActionPerformed

    private void bangkuB1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB1ButtonActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "1";
    }//GEN-LAST:event_bangkuB1ButtonActionPerformed

    private void bangkuB2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB2ButtonActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "2";
    }//GEN-LAST:event_bangkuB2ButtonActionPerformed

    private void bangkuB3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB3ButtonActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "3";
    }//GEN-LAST:event_bangkuB3ButtonActionPerformed

    private void bangkuB4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuB4ButtonActionPerformed
        // TODO add your handling code here:
        baris = "b";
        nomer = "4";
    }//GEN-LAST:event_bangkuB4ButtonActionPerformed

    private void bangkuC1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC1ButtonActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "1";
    }//GEN-LAST:event_bangkuC1ButtonActionPerformed

    private void bangkuC2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC2ButtonActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "2";
    }//GEN-LAST:event_bangkuC2ButtonActionPerformed

    private void bangkuC3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangkuC3ButtonActionPerformed
        // TODO add your handling code here:
        baris = "c";
        nomer = "3";
    }//GEN-LAST:event_bangkuC3ButtonActionPerformed

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
            // TODO add your handling code here:
        String pilihan = pilih.getSelectedItem().toString();
        isi1.isijam(jamt, pilihan);
        isi1.isistudio(studio, pilihan);
        isi1.isiharga(harga, pilihan);
    }//GEN-LAST:event_refreshActionPerformed

    private void cetakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakButtonActionPerformed
        // TODO add your handling code here:
        String dipilih = baris+nomer;
        String stud = studio.getText();
        isi1.pilihkursi(dipilih, stud);
        cetakkan();
        dispose();
    }//GEN-LAST:event_cetakButtonActionPerformed
    private void cetakkan(){
        cetak tiket = new cetak();
        tiket.setVisible(true);
        tiket.setJdl(pilih.getSelectedItem().toString());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String tanggal = dtf.format(now).toString();
        tiket.setTgl(tanggal);
        tiket.setJamm(jamt.getText());
        tiket.setH(baris);
        tiket.setA(nomer);
        tiket.setS(studio.getText());
        tiket.setHr(harga.getText());
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bangkuA1Button;
    private javax.swing.JButton bangkuA2Button;
    private javax.swing.JButton bangkuA3Button;
    private javax.swing.JButton bangkuA4Button;
    private javax.swing.JButton bangkuB1Button;
    private javax.swing.JButton bangkuB2Button;
    private javax.swing.JButton bangkuB3Button;
    private javax.swing.JButton bangkuB4Button;
    private javax.swing.JButton bangkuC1Button;
    private javax.swing.JButton bangkuC2Button;
    private javax.swing.JButton bangkuC3Button;
    private javax.swing.JButton bangkuC4Button;
    private javax.swing.JButton cetakButton;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jamt;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel studio;
    // End of variables declaration//GEN-END:variables
}
