/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbogui;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class pilihanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form pilihanAdmin
     */
    public Connection kon;
    
        
    public pilihanAdmin() {
        initComponents();
        
        try{
            String DB="jdbc:mysql://localhost/horebioskop";
            String user ="root";
            String pw ="";
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            kon = (Connection) DriverManager.getConnection(DB, user, pw);
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampil();
        
        
    }
    private void tampil(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Film");
        model.addColumn("Judul");
        model.addColumn("Jam Tayang");
        model.addColumn("Genre");
        model.addColumn("Studio");
        model.addColumn("Harga");
        tabel.setModel(model);
         try{
            String sqlv="select * from movie";
            Statement stm = kon.createStatement();
            ResultSet res = stm.executeQuery(sqlv);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
                
            }   
        }catch(SQLException e){
            e.printStackTrace();
        }
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        judulnya = new javax.swing.JTextField();
        jamnya = new javax.swing.JTextField();
        stdnya = new javax.swing.JComboBox<>();
        gennya = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        harganya = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idnya = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jTabbedPane2.setName(""); // NOI18N
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel2.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Judul             :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 73, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Jam Tayang :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Studio           :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 73, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Genre           :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 73, -1));

        judulnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulnyaActionPerformed(evt);
            }
        });
        jPanel2.add(judulnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 443, -1));
        jPanel2.add(jamnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 443, -1));

        stdnya.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        stdnya.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4" }));
        jPanel2.add(stdnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 443, -1));
        jPanel2.add(gennya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 443, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Tambah Film");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 44));

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 110, 44));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Harga           :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 73, -1));
        jPanel2.add(harganya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 443, -1));

        jLabel8.setText("ID Movie         :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        idnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnyaActionPerformed(evt);
            }
        });
        jPanel2.add(idnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 443, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/5.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 600, 470));

        jTabbedPane2.addTab("Tambah Film", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("Edit Film");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 110, 44));

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setText("Hapus Film");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 110, 44));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 565, 290));

        jButton2.setText("refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 110, 44));

        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 560, 44));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbogui/5.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 600, 480));

        jTabbedPane2.addTab("Daftar Film", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void judulnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulnyaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String judul = judulnya.getText();
        String id = idnya.getText();
        String jam = jamnya.getText();
        String gen = gennya.getText();
        String stu = String.valueOf(stdnya.getSelectedItem());
        String hrg = harganya.getText();
        String sql;
        
        if(judul.isEmpty() || id.isEmpty() || jam.isEmpty() || gen.isEmpty() || stu.isEmpty() || hrg.isEmpty())
            JOptionPane.showMessageDialog(null, "Harap isi semua form");
        else {
            try {
                sql="insert into movie values('"+id+"','"+judul+"','"+jam+"','"+gen+"','"+stu+"','"+hrg+"')";
                PreparedStatement ps = kon.prepareStatement(sql);
                ps.executeUpdate(sql);

                JOptionPane.showMessageDialog(null, "Film berhasil ditambahkan" );
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnyaActionPerformed
   
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int dpl = tabel.getSelectedRow();
        String idd = tabel.getValueAt(dpl, 0).toString();
        String judd = tabel.getValueAt(dpl, 1).toString();
        String jamm = tabel.getValueAt(dpl, 2).toString();
        String studd = tabel.getValueAt(dpl, 4).toString();
        String genn = tabel.getValueAt(dpl, 3).toString();
        String harr = tabel.getValueAt(dpl, 5).toString();
        edit edit1 = new edit();
        edit1.setVisible(true);
        edit1.setID(idd);
        edit1.setJud(judd);
        edit1.setJam(jamm);
        edit1.setStud(studd);
        edit1.setGenre(genn);
        edit1.setHarga(harr);
            dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    private void hapus(){
        int dpl = tabel.getSelectedRow();
        String id = tabel.getValueAt(dpl, 0).toString();
        PreparedStatement pst;
        System.out.println(id);
        String sql = "delete from movie where id_movie = '"+id+"'";
        
        try{
            pst = kon.prepareStatement(sql);
            pst.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(null, "Film berhasil dihapus" );
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     hapus();
     tampil();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new TampilanAwal().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new TampilanAwal().setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gennya;
    private javax.swing.JTextField harganya;
    private javax.swing.JTextField idnya;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jamnya;
    private javax.swing.JTextField judulnya;
    private javax.swing.JComboBox<String> stdnya;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
